# -*- coding: utf-8 -*-
"""SQLite Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrxPvzs2MyYjgyb1xWMWm9mdYN5z7OCA
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

conn = sqlite3.connect("/content/Sales_dataset.csv")
cursor = conn.cursor()

import sqlite3
import pandas as pd

# Load CSV file into pandas DataFrame
df = pd.read_csv("/content/Sales_dataset.csv")
print("CSV loaded:")
print(df.head())

# Connect to SQLite DB (creates file if not exists)
conn = sqlite3.connect("sales_data.db")

# Save DataFrame into SQLite table
df.to_sql("sales", conn, if_exists="replace", index=False)
print("Data saved into SQLite database.")

print(df.columns)

query1 = """
SELECT
    Gender,
    COUNT(*) AS total_customers,
    ROUND(SUM(Revenue_Total), 2) AS total_revenue
FROM sales
GROUP BY Gender
"""
df1 = pd.read_sql_query(query1, conn)
print("Revenue by Gender:")
print(df1)

query2 = "SELECT ROUND(SUM(Revenue_Total), 2) AS total_revenue FROM sales"
result2 = pd.read_sql_query(query2, conn)
print("Total revenue from all customers:")
print(result2)

query3 = """
SELECT
    Pay_Method,
    ROUND(SUM(Revenue_Total), 2) AS total_revenue
FROM sales
GROUP BY Pay_Method
"""
result3 = pd.read_sql_query(query3, conn)
print("Revenue by Payment Method:")
print(result3)

# Plot a bar chart
result3.plot(kind='bar', x='Pay_Method', y='total_revenue', color='lightgreen', legend=False)
plt.title("Total Revenue by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Revenue (₹)")
plt.tight_layout()
plt.savefig("revenue_by_payment.png")
plt.show()

